### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by JobGetabu** [Ian-Cornelius/ATOnDroid#2]
If the logcat is showing this.

Process: com.job.atdonate, PID: 32003
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at com.africastalking.proto.SdkServerServiceGrpc$SdkServerServiceBlockingStub.getToken(SdkServerServiceGrpc.java:172)
        at com.africastalking.services.Service.fetchToken(Service.java:147)
        at com.africastalking.services.Service.<init>(Service.java:106)
        at com.africastalking.services.SmsService.<init>(SmsService.java:27)
        at com.africastalking.services.Service.newInstance(Service.java:189)
        at com.africastalking.AfricasTalking.getSmsService(AfricasTalking.java:81)
        at com.job.atdonate.ui.DonateFragment$1.doInBackground(DonateFragment.java:268)
        at com.job.atdonate.ui.DonateFragment$1.doInBackground(DonateFragment.java:255)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.8.101 (port 8080) after 90000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:189)
        at libcore.io.IoBridge.connect(IoBridge.java:127)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:168)
        at java.net.Socket.startupSocket(Socket.java:609)
        at java.net.Socket.<init>(Socket.java:235)
        at io.grpc.okhttp.OkHttpClientTransport$1.run(OkHttpClientTransport.java:412)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by JobGetabu** [comment]
Solved by
Selecting server on the run drop down, and then click the run button
**Don't exit the loop since it keeps the server alive**
Then you won't hit the **SocketTimeoutException**

**Comment by Ian-Cornelius** [comment]
Great observation @JobGetabu.
